In [1]:
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#%matplotlib inline

In [2]:
df_path = "/Users/tomii/tmp/AnalysisResult/pv_stim_pandas.csv"

In [3]:
df = pd.read_csv(df_path)

In [4]:
data = np.zeros([len(df), 4])
for i in range(len(df)):
    s = df.loc[i,:]    
    vec_pre = (s.stim_x - s.pre_x) + 1j*(s.stim_y - s.pre_y)
    shift = np.abs(((s.pst_x - s.pre_x) + 1j*(s.pst_y - s.pre_y)))
    
    d = np.array([s.stim_phase, np.abs(vec_pre), np.angle(vec_pre) - s.fb_angle, shift])
    data[i,:] = d
    #print i, s.sample, s.session, d

plt.hist(data[:,3], np.arange(1,40,2))
plt.show()

In [5]:
#thre = np.max(data[:,2])*0.5
thre = 18

x =  np.cos(data[:,0])
y = np.sin(data[:,0])
x *= np.absolute(np.cos(data[:,2]))
y *= np.absolute(np.cos(data[:,2]))

rgb = (np.c_[data[:,3], data[:,3], data[:,3]] > thre)*1.0
#rgb = np.c_[data[:,3], data[:,3], data[:,3]] / np.max(data[:,3])
#rgb[:,1] = 0.0
#rgb[:,2] = 1-rgb[:,0]

fig, ax = plt.subplots()
ax.scatter(x, y, s=100, facecolors=rgb)
plt.xlim([-1.5,1.5])
plt.ylim([-1.5,1.5])
plt.show()

/usr/local/lib/python2.7/site-packages/matplotlib/collections.py:571: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):


In [6]:
#thre = np.max(data[:,2])*0.5
#thre = np.mean(data[:,2])

x =  np.cos(data[:,0])
y = np.sin(data[:,0])
x *= data[:,1]
y *= data[:,1]
#x /= np.max(data[:,1])
#y /= np.max(data[:,1])

rgb = (np.c_[data[:,3], data[:,3], data[:,3]] > thre)*1.0
#rgb = np.c_[data[:,3], data[:,3], data[:,3]] / np.max(data[:,3])
#rgb[:,1] = 0.0
#rgb[:,2] = 1-rgb[:,0]

fig, ax = plt.subplots()
ax.scatter(x, y, s=100, facecolors=rgb)
plt.xlim([-40,40])
plt.ylim([-40,40])
plt.show()

print np.mean(data[:,1])

21.3125690317


In [7]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

l = data[:,1] 
l /= np.max(l)
x =  np.cos(data[:,0])
y = np.sin(data[:,0])
x *= np.absolute(np.cos(data[:,2]))
y *= np.absolute(np.cos(data[:,2]))
x *= l
y *= l
z = l * np.absolute(np.sin(data[:,2]))

thre = 18
rgb = (np.c_[data[:,3], data[:,3], data[:,3]] > thre)*1.0
#rgb = np.c_[data[:,3], data[:,3], data[:,3]] / np.max(data[:,3])
#rgb[:,1] = 0.0
#rgb[:,2] = 1-rgb[:,0]

ax.scatter(x, y, z, s=50, c=rgb)
#plt.xlim([-1.5,1.5])
#plt.ylim([-1.5,1.5])
#plt.zlim([-1.5,1.5])
plt.show()

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/mplot3d/axes3d.py:1094: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if self.button_pressed in self._rotate_btn:


In [11]:
print df.loc[list(np.where(data[:,0]   <  -0.5*np.pi )[0]), ["sample", "session", "frame_start"]]
print data[np.where(data[:,0]   <  -0.5*np.pi ), :]

        sample  session  frame_start
10  20160907-3       11          400
11  20160907-3       17          360
13  20161019-1       18          370
14  20161019-1       19          370
15  20161019-2        6          170
18  20161019-2        9          190
27  20161019-2       18          190
28  20161019-2       19          200
29  20161019-2       20          210
35  20161019-3       25          255
[[[ -2.48086182  -4.03572208   3.60555128]
  [ -2.84469657  -1.45209099   9.48683298]
  [ -2.71337265  -2.64152391   5.        ]
  [ -1.71351379  -3.31626485  23.70653918]
  [ -1.96593969  -2.2794226   38.05259518]
  [ -2.93230223  -1.9513027   35.05709629]
  [ -2.80538421  -3.32144615   7.28010989]
  [ -2.42557414  -3.4276441    3.60555128]
  [ -1.66214547  -3.60524026   4.47213595]
  [ -2.04189594   0.55575572  25.8069758 ]]]
