In [1]:
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#%matplotlib inline

In [2]:
def phase_add(a, b):
    a_ = np.cos(a) + np.sin(a)*1j
    b_ = np.cos(b) + np.sin(b)*1j
    return np.angle(a_*b_)

def phase_statics(X):
    a = 0
    for x in X: a += ( np.cos(x) + np.sin(x)*1j)
    a /= len(X)
    return np.angle(a), 1-np.abs(a)

def getAngleDensityMap(hist_phase, size = 512):
    img = np.zeros([size, size])
    center = [size / 2, size/2]
    print hist_phase
    for i in range(size): # y 
        for j in range(size): # x
            pos = ( j - center[1] ) + 1j*( i - center[0] )
            if np.abs(pos) < size / 2:
                img[i,j] = hist_phase[int( - ( np.angle( pos ) + np.pi ) / (0.1*np.pi) )]
    return img


In [3]:
data_dir = "/Volumes/HD-PLFU3/AnalysisResult/"
df_path = "/Users/tomii/tmp/AnalysisResult/pv_stim_pandas.csv"
winrad = 4

In [4]:
df = pd.read_csv(df_path)
df["stim_phase"] = np.zeros(len(df))
for i in range(len(df)):
    s = df.loc[i,:]    
    sess_dir = data_dir+"{0}/C001H001S{1:0>4}/".format(s.sample, s.session)
    print i, sess_dir
    
    pmap_data = np.load(sess_dir+'/pmap.npy')
    phases = pmap_data[s.frame_start, s.stim_x - winrad:s.stim_x+winrad, s.stim_y - winrad:s.stim_y+winrad]
    phases = phases.flatten()
    s.stim_phase, _ = phase_statics(phases)
    df.loc[i,:] = s
df.to_csv(df_path, index=False)

0 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0008/
1 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0014/
2 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0015/
3 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0017/
4 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0034/
5 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0035/
6 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0036/
7 /Volumes/HD-PLFU3/AnalysisResult/20140911-2/C001H001S0038/
8 /Volumes/HD-PLFU3/AnalysisResult/20160907-3/C001H001S0006/
9 /Volumes/HD-PLFU3/AnalysisResult/20160907-3/C001H001S0010/
10 /Volumes/HD-PLFU3/AnalysisResult/20160907-3/C001H001S0011/
11 /Volumes/HD-PLFU3/AnalysisResult/20160907-3/C001H001S0017/
12 /Volumes/HD-PLFU3/AnalysisResult/20160907-3/C001H001S0022/
13 /Volumes/HD-PLFU3/AnalysisResult/20161019-1/C001H001S0018/
14 /Volumes/HD-PLFU3/AnalysisResult/20161019-1/C001H001S0019/
15 /Volumes/HD-PLFU3/AnalysisResult/20161019-2/C001H001S0006/
16 /Volumes/HD-PLF

/usr/local/lib/python2.7/site-packages/IPython/kernel/__main__.py:9: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/usr/local/lib/python2.7/site-packages/pandas/core/generic.py:1951: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [5]:
df = pd.read_csv(df_path)
df

sample  session  frame_start  frame_end  roi_top  roi_bottom  \
0   20140911-2        8          322        342        0         128   
1   20140911-2       14          306        328       30         128   
2   20140911-2       15          282        312        0         128   
3   20140911-2       17          282        312        0         128   
4   20140911-2       34          302        315       70         128   
5   20140911-2       35          302        337        0         128   
6   20140911-2       36          282        312        0         128   
7   20140911-2       38          302        332        0         128   
8   20160907-3        6          300        313       69         128   
9   20160907-3       10          360        376        0         128   
10  20160907-3       11          400        401        0         128   
11  20160907-3       17          360        363        0         128   
12  20160907-3       22          329        361       65         128   
13  20161019-1       18          370        406       83         128   
14  20161019-1       19          370        406       50         128   
15  20161019-2        6          170        206        0         128   
16  20161019-2        7          160        190        0         128   
17  20161019-2        8          140        166        0         128   
18  20161019-2        9          190        215        0         128   
19  20161019-2       10          150        176        0         128   
20  20161019-2       11          250        286        0         128   
21  20161019-2       12          130        166        0         128   
22  20161019-2       13          140        166        0         128   
23  20161019-2       14          150        176        0         128   
24  20161019-2       15          160        186        0         128   
25  20161019-2       16          170        196        0         128   
26  20161019-2       17          180        206        0         128   
27  20161019-2       18          190        216        0         128   
28  20161019-2       19          200        226        0         128   
29  20161019-2       20          210        236        0         128   
30  20161019-2       21          230        256        0         128   
31  20161019-2       22          250        276        0         128   
32  20161019-2       23          270        296        0         128   
33  20161019-2       24          290        326        0         128   
34  20161019-3       24          260        286        0         128   
35  20161019-3       25          255        287        0         128   
36  20161021-1        9          175        205       80         128   
37  20161021-1       10          175        211        0         128   
38  20161021-1       11          175        211        0         128   
39  20161021-1       12          185        221       82         128   
40  20161021-1       13          172        211        0         128   
41  20161021-1       14          185        221       80         128   
42  20161021-1       16          195        241       90         128   
43  20161021-2       10          190        216        0         128   
44  20161021-2       11          200        210        0         128   
45  20161021-2       12          210        217        0         128   

    roi_left  roi_right  stim_x  stim_y  pre_x  pre_y  pst_x  pst_y  \
0         60        128      78      60     75     65     68     60   
1          0        128      78      60     82     51     74     35   
2          0        128      78      60     83     74     84     67   
3          0        128      78      60     87     68     84     55   
4          0        128      78      60     68     75     69     73   
5          0        128      78      60     72     74     53     40   
6          0        128      78      60     85     74     87     61   
7          0        128      78      60     75     47  

In [6]:
data = np.zeros([len(df), 4])
for i in range(len(df)):
    s = df.loc[i,:]    
    sess_dir = data_dir+"{0}/C001H001S{1:0>4}/".format(s.sample, s.session)
    #print i, sess_dir
    
    vec_pre = (s.stim_x - s.pre_x) + 1j*(s.stim_y - s.pre_y)
    shift = np.abs(((s.pst_x - s.pre_x) + 1j*(s.pst_y - s.pre_y)))
    
    d = np.array([s.stim_phase, np.abs(vec_pre), np.angle(vec_pre) - s.fb_angle, shift])
    data[i,:] = d
    print i, s.sample, s.session, d

0 20140911-2 8 [ 1.23525972  5.83095189 -2.08003501  8.60232527]
1 20140911-2 14 [  0.63330154   9.8488578    0.93936247  17.88854382]
2 20140911-2 15 [  0.78260306  14.86606875  -2.96347845   7.07106781]
3 20140911-2 17 [ -0.42930068  12.04159458  -3.4646085   13.34166406]
4 20140911-2 34 [  0.98019815  18.02775638  -2.03245191   2.23606798]
5 20140911-2 35 [  1.08595941  15.23154621  -2.21556272  38.94868419]
6 20140911-2 36 [ -0.46645058  15.65247584  -3.08410212  13.15294644]
7 20140911-2 38 [  0.41995919  13.34166406   0.2943393   15.5241747 ]
8 20160907-3 6 [ -1.00477474  26.62705391  -4.09834636  14.14213562]
9 20160907-3 10 [  2.60706737  26.01922366  -1.59361519  24.59674775]
10 20160907-3 11 [ -2.48086182  22.8035085   -4.03572208   3.60555128]
11 20160907-3 17 [ -2.84469657  29.15475947  -1.45209099   9.48683298]
12 20160907-3 22 [  1.17900728   4.24264069  -0.76977443  34.6554469 ]
13 20161019-1 18 [ -2.71337265  18.11077028  -2.64152391   5.        ]
14 20161019-1 19 [ -1.

In [7]:
#thre = np.max(data[:,2])*0.5
thre = np.mean(data[:,2])

x =  np.cos(data[:,0])
y = np.sin(data[:,0])
x *= np.absolute(np.cos(data[:,2]))
y *= np.absolute(np.cos(data[:,2]))

#rgb = (np.c_[data[:,2], data[:,2], data[:,2]] > thre)*1.0
rgb = np.c_[data[:,3], data[:,3], data[:,3]] / np.max(data[:,3])
#rgb[:,1] = 0.0
#rgb[:,2] = 1-rgb[:,0]

fig, ax = plt.subplots()
ax.scatter(x, y, s=100, facecolors=rgb)
plt.xlim([-1.5,1.5])
plt.ylim([-1.5,1.5])
plt.show()

/usr/local/lib/python2.7/site-packages/matplotlib/collections.py:571: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):


In [9]:
#thre = np.max(data[:,2])*0.5
thre = np.mean(data[:,2])

x =  np.cos(data[:,0])
y = np.sin(data[:,0])
x *= data[:,1]
y *= data[:,1]
#x /= np.max(data[:,1])
#y /= np.max(data[:,1])

#rgb = (np.c_[data[:,2], data[:,2], data[:,2]] > thre)*1.0
rgb = np.c_[data[:,3], data[:,3], data[:,3]] / np.max(data[:,3])
#rgb[:,1] = 0.0
#rgb[:,2] = 1-rgb[:,0]

fig, ax = plt.subplots()
ax.scatter(x, y, s=100, facecolors=rgb)
plt.xlim([-40,40])
plt.ylim([-40,40])
plt.show()

print np.mean(data[:,1])

21.3125690317


In [15]:
np.cos(2.0)

-0.41614683654714241

In [14]:
np.max(data[:,2])

38.948684188300895

In [11]:
print df.loc[list(np.where(data[:,0]   <  -0.5*np.pi )[0]), ["sample", "session", "frame_start"]]
print data[np.where(data[:,0]   <  -0.5*np.pi ), :]

        sample  session  frame_start
10  20160907-3       11          400
11  20160907-3       17          360
13  20161019-1       18          370
14  20161019-1       19          370
15  20161019-2        6          170
18  20161019-2        9          190
27  20161019-2       18          190
28  20161019-2       19          200
29  20161019-2       20          210
35  20161019-3       25          255
[[[ -2.48086182  -4.03572208   3.60555128]
  [ -2.84469657  -1.45209099   9.48683298]
  [ -2.71337265  -2.64152391   5.        ]
  [ -1.71351379  -3.31626485  23.70653918]
  [ -1.96593969  -2.2794226   38.05259518]
  [ -2.93230223  -1.9513027   35.05709629]
  [ -2.80538421  -3.32144615   7.28010989]
  [ -2.42557414  -3.4276441    3.60555128]
  [ -1.66214547  -3.60524026   4.47213595]
  [ -2.04189594   0.55575572  25.8069758 ]]]
